apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: new-mysql-statefulset
spec:
  replicas: 1
  serviceName: mysql
  selector:
    matchLabels:
      app: new-mysql
  template:
    metadata:
      labels:
        app: new-mysql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mysql
          image: mysql:5.6
          ports:
            - name: tpc
              protocol: TCP
              containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password
          volumeMounts:
            - name: new-mysql-data-claim
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: new-mysql-data-claim
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi

