apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-mysql-0
  labels:
    app: mysql
    app.kubernetes.io/name: mysql
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
