apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todo-volume-todo-mysql-0
spec:
  storageClassName: sc-local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
