apiVersion: v1
kind: PersistentVolume
metadata:
  name: todo-pv
  labels:
    type: local
spec:
  storageClassName: sc-local
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
