---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydb
  labels:
    app: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: mydb
        image: mysql:5.7
        imagePullPolicy: Always
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: phone-secrets
              key: db_root_password
        ports:
        - containerPort: 3306
          name: mydb
        volumeMounts:
          - name: mysql-persistent-storage
            mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim


---
apiVersion: v1
kind: Service
metadata:
  name: mydb
  labels:
    app: db
spec:
  ports:
  - port: 3306
    protocol: TCP
    name: mydb
  selector:
    app: db
  type: ClusterIP
